---
- name: Template jenkins.repo
  template: src=jenkins.repo dest=/etc/yum.repos.d/jenkins.repo mode=0644

- name: Install openjdk
  yum: pkg={{ item }} state=present
  with_items:
    - java-1.6.0-openjdk
    - java-1.6.0-openjdk-devel

- name: Install Jenkins
  yum: pkg={{ item }} state=present
  with_items:
    - jenkins

- name: change port 8080 to 8082
  lineinfile: dest=/etc/sysconfig/jenkins state=present regexp="JENKINS_PORT"
              line="JENKINS_PORT=\"{{ jenkins_port }}\""

- name: ensure jenkins is running automatically at boot time
  service: name=jenkins state=started enabled=yes

- name: Template nginx/conf.d/jenkins.conf
  template: src=nginx_jenkins.conf.j2 dest=/etc/nginx/conf.d/jenkins.conf mode=0644

- name: restart nginx
  service: name=nginx state=restarted

- name: Download jenkins-cli.jar
  get_url: url=http://127.0.0.1:8082/jnlpJars/jenkins-cli.jar dest=/var/lib/jenkins/jenkins-cli.jar
